plugins {
    id 'com.android.application'
}

android {
    namespace 'com.playface.v2'
    compileSdk 34

    defaultConfig {
        applicationId "com.playface.v2"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "0.2"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
